# Buildpacks to include in builder
[[buildpacks]]
#id = "samples/java-maven"
#version = "0.0.1"
#uri = "../../buildpacks/java-maven"
uri = "docker://jandebryan/my-sample-java-maven:latest"

[[buildpacks]]
id = "samples/kotlin-gradle"
version = "0.0.1"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
uri = "docker://cnbs/sample-package:hello-universe"

# Order used for detection
[[order]]
[[order.group]]
id = "my-samples/java-maven"
version = "0.0.2"

[[order]]
[[order.group]]
id = "samples/kotlin-gradle"
version = "0.0.1"

[[order]]
[[order.group]]
id = "samples/hello-universe"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.alpine"
#run-image = "cnbs/sample-stack-run:alpine"
#build-image = "cnbs/sample-stack-build:alpine"
run-image = "jandebryan/stack-run:alpine"
build-image = "jandebryan/stack-build:alpine"
